name: (Alpha test) - Deploy ESTEC backend

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [alpha_test]
  push:
    branches: [alpha_test]

env:
  NODE_VERSION: 16.x

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout latest commit (Alpha)
        uses: actions/checkout@v4
      - name: Setup Node.js environment (version ${{ env.NODE_VERSION }})
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'
      - name: Install Dependencies
        run: |
          yarn
      - name: Make env file for testing
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_TEST_VALUE: '<This is a sample test value>'
          file_name: .env.test
          fail_on_empty: false
      - name: Run test
        run: |
          cat .env.test
          yarn test-unit

  Deploy:
    needs: [test]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::617443366113:role/GithubActionsDeploymentRole
          aws-region: ap-southeast-1
      - name: Install Dependencies
        run: |
          yarn global add serverless
          yarn
      - name: Run Serverless deploy
        run: |
          serverless deploy --stage alpha --force
