name: (Alpha) - Test

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [alpha]

env:
  STAGE: 'alpha'
  PROVIDER_NAME: 'aws'
  REGION: 'ap-southeast-1'
  NODE_VERSION: '20.x'
  TZ: 'Asia/Ho_Chi_Minh'

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout latest commit of branch ${{ github.ref_name }}
        uses: actions/checkout@v4
      - name: Setup Node.js environment (version ${{ env.NODE_VERSION }})
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'
      - name: Install Dependencies
        run: |
          yarn
      - name: Make env file for testing
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_TEST_VALUE: '<This is a sample test value>'
          file_name: .env.test
          fail_on_empty: false
      - name: Run test
        run: |
          cat .env.test
          yarn test
