name: (Alpha) - Deploy ESTEC backend

on:
  push:
    branches: [alpha]

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout latest commit (Alpha)
        uses: actions/checkout@v2
      - name: Setup Node.js environment (version 16.x)
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'yarn'
      - name: Install Dependencies
        run: |
          yarn
      - name: Make env file for testing
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_TEST_VALUE: '<This is a sample test value>'
          file_name: .env.test
          fail_on_empty: false
      - name: Run test
        run: |
          cat .env.test
          yarn test-unit
